/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UUID = string;
export type HtmlFilename = string;
export type ImageFilename = string;
export type StylesFilename = string;
export type FontFilename = string;
export type PageNumber = string;

export interface Manifest {
  metadata?: Metadata;
  paths?: {
    footnotes?: string;
    source?: FilePaths;
    epub?: FilePaths;
    output?: OutputPaths;
  };
  files: (
    | HtmlFilename
    | ImageFilename
    | StylesFilename
    | FontFilename
    | Section
    | Image
    | Content
    | Factory
    | Styles
    | Font
  )[];
  [k: string]: unknown;
}
export interface Metadata {
  title?: string;
  pubId?: UUID;
  author?: string;
  publisher?: string;
  [k: string]: unknown;
}
export interface FilePaths {
  htmlPath?: string;
  imagePath?: string;
  stylePath?: string;
  fontPath?: string;
  navPath?: string;
}
export interface OutputPaths {
  epubPath?: string;
  explodedEpubPath?: string;
  combinedHtmlPath?: string;
  combinedPathToStyles?: string;
}
export interface Section {
  _tag: "SECTION";
  filename: ImageFilename;
  title: string;
  level?: number;
  landmark?: string;
  toc?: boolean;
  pageNumber?: PageNumber;
}
export interface Image {
  _tag: "IMAGE";
  caption: string;
  filename: ImageFilename;
  level?: number;
  landmark?: string;
  illustration?: boolean;
  toc?: boolean;
  pageNumber?: PageNumber;
}
export interface Content {
  _tag: "CONTENT";
  title?: string;
  filename: HtmlFilename;
  landmark?: string;
  toc?: boolean;
  bodyClass?: string;
}
export interface Factory {
  _tag: "FACTORY";
  title?: string;
  filename: HtmlFilename;
  landmark?: string;
  toc?: boolean;
  factory: string;
  bodyClass?: string;
  pageNumber?: PageNumber;
}
export interface Styles {
  _tag: "STYLES";
  filename: StylesFilename;
}
export interface Font {
  _tag?: "FONT";
  filename?: FontFilename;
  [k: string]: unknown;
}
